//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Validation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Validation", typeof(Validation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already exist. please try another.
        /// </summary>
        public static string ErrorMsg_EmailExist {
            get {
                return ResourceManager.GetString("ErrorMsg_EmailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to complete the operation. please try again.
        /// </summary>
        public static string ErrorMsg_FailedOperation {
            get {
                return ResourceManager.GetString("ErrorMsg_FailedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out failed.
        /// </summary>
        public static string ErrorMsg_FailedSignOut {
            get {
                return ResourceManager.GetString("ErrorMsg_FailedSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid inputs. please try again.
        /// </summary>
        public static string ErrorMsg_InvalidInputs {
            get {
                return ResourceManager.GetString("ErrorMsg_InvalidInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password incorrect. please try again.
        /// </summary>
        public static string ErrorMsg_LoginFail {
            get {
                return ResourceManager.GetString("ErrorMsg_LoginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No white space allowed.
        /// </summary>
        public static string ErrorMsg_NoWhiteSpace {
            get {
                return ResourceManager.GetString("ErrorMsg_NoWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password not match.
        /// </summary>
        public static string ErrorMsg_PasswordNotMatch {
            get {
                return ResourceManager.GetString("ErrorMsg_PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be between 6 and 20 characters and contain : 
        ///one uppercase letter, one lowercase letter, one digit and one special character..
        /// </summary>
        public static string ErrorMsg_PasswordValidation {
            get {
                return ResourceManager.GetString("ErrorMsg_PasswordValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} and at most {1} characters long..
        /// </summary>
        public static string ErrorMsg_TextLength {
            get {
                return ResourceManager.GetString("ErrorMsg_TextLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is locked out.
        /// </summary>
        public static string ErrorMsg_UserLockedOut {
            get {
                return ResourceManager.GetString("ErrorMsg_UserLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already exist. please try another.
        /// </summary>
        public static string ErrorMsg_UsernameExist {
            get {
                return ResourceManager.GetString("ErrorMsg_UsernameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation error. please try again.
        /// </summary>
        public static string ErrorMsg_ValidationError {
            get {
                return ResourceManager.GetString("ErrorMsg_ValidationError", resourceCulture);
            }
        }
    }
}
